apiVersion: 1

datasources:
  - name: SENTINEL_PostgreSQL
    type: postgres
    uid: sentinel-pg
    url: sentinel_postgres:5432
    user: sentinel
    secureJsonData:
      password: sentinel_pass
    jsonData:
      database: sentinel_db
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
